export const API_ACTION = "API_ACTION";

export const WEATHER = "WEATHER";
export const WEATHER_REQUESTED = "WEATHER_REQUESTED";
export const WEATHER_RECEIVED = "WEATHER_RECEIVED";
export const WEATHER_FAILED = "WEATHER_FAILED";

export const LOCATIONS_CITY = "LOCATIONS_CITY";
export const LOCATIONS_CITY_REQUESTED = "LOCATIONS_CITY_REQUESTED";
export const LOCATIONS_CITY_RECEIVED = "LOCATIONS_CITY_RECEIVED";
export const LOCATIONS_CITY_FAILED = "LOCATIONS_CITY_FAILED";

export const LOCATIONS_LATLON = "LOCATIONS_LATLON";
export const LOCATIONS_LATLON_REQUESTED = "LOCATIONS_LATLON_REQUESTED";
export const LOCATIONS_LATLON_RECEIVED = "LOCATIONS_LATLON_RECEIVED";
export const LOCATIONS_LATLON_FAILED = "LOCATIONS_LATLON_FAILED";

export const SET_LOCATION = "SET_LOCATION";
