export const API_ACTION = "API_ACTION";

export const WEATHER = "WEATHER";
export const WEATHER_REQUESTED = "WEATHER_REQUESTED";
export const WEATHER_RECEIVED = "WEATHER_RECEIVED";
export const WEATHER_FAILED = "WEATHER_FAILED";

export const LOCATIONS = "LOCATIONS";
export const LOCATIONS_REQUESTED = "LOCATIONS_REQUESTED";
export const LOCATIONS_RECEIVED = "LOCATIONS_RECEIVED";
export const LOCATIONS_FAILED = "LOCATIONS_FAILED";
